version: '3.7'
services:
  app-server:
    build:
      context: . # same dir
      dockerfile: Dockerfile_with_mvn
    ports:
      - "8080:8080" # Forward the exposed port 9090 on the container to port 90 on the host machine
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      # this will override application.properties values as far as I can tell
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shapeshop?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#      jdbc:mysql://mysql-db2:3306/customer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: shapeshop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # Persist data
      - "db-data2:/var/lib/mysql"
      # Mount the schema file
      - "./SCHEMA.sql:/docker-entrypoint-initdb.d/SCHEMA.sql"
      # init data here :
      - "./TEST_DATA.sql:/docker-entrypoint-initdb.d/TEST_DATA.sql"
    networks:
      - backend

volumes:
  db-data2:

networks:
  backend:
