apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-test
  name: test-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-test
    spec:
      containers:
      - image: shapeshop
        name: shapeshop
        resources: {}
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-test
  name: test-test
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-test
  type: ClusterIP
status:
  loadBalancer: {}
