
spring:  
  thymeleaf:  
    cache: false  
  security:  
    oauth2:  
      client:  
        registration:  
          github:  
            client-id: b6a8b4767bf93102a5d3  
            client-secret: 4f4d329e579472f3a299a29ce48e84d7dc470ec0